# Generated by Django 5.1.7 on 2025-03-18 16:51

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=courses.models.handle_upload
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("any", "Anyone"),
                            ("email_required", "Email Required"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pub", "Published"),
                            ("draft", "Draft"),
                            ("soon", "Coming Soon"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
