# Generated by Django 5.1.7 on 2025-03-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('any', 'Anyone'), ('email_required', 'Email Required')], default='email_required', max_length=20),
        ),
    ]
