# Generated by Django 5.1.7 on 2025-03-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_public_id_alter_lesson_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='timpestamp',
            new_name='timestamp',
        ),
    ]
